framework:
    messenger:
        failure_transport: failed

        transports:
            async: 'doctrine://default'
            failed: 'doctrine://default?queue_name=failed'

        routing:
        # Solo dejamos el env√≠o de emails si existe, si no, lo comentamos
        # 'Symfony\Component\Mailer\Messenger\SendEmailMessage': async
