framework:
    router:
        # Hemos cambiado %env(DEFAULT_URI)% por la URL fija de tu servidor local
        default_uri: 'http://127.0.0.1:8000'

when@prod:
    framework:
        router:
            strict_requirements: null
